name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [3.0.x, 3.1.x, 5.0.x]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Install dependencies
      run: cd src && dotnet restore
    - name: Build
      run: cd src && dotnet build --configuration Release --no-restore
    - name: Unit Test With Coverage Report
      run: |
        printenv
        cd ./tests/Atrea.PolicyEngine.Tests/
        dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish Coverage Report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./tests/Atrea.PolicyEngine.Tests/TestResults/coverage.info
