name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [netcoreapp3.1, net5.0, net6.0]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x        
    - name: Install dependencies
      run: cd src && dotnet restore
    - name: Build
      run: cd src && dotnet build --configuration Release --no-restore
    - name: Unit Test With Coverage Report
      run: |
        cd ./tests/Atrea.PolicyEngine.Tests/
        dotnet test --framework=${{ matrix.dotnet }} --no-restore /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Upload Code Coverage Results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report-${{ matrix.dotnet }}
        path: ./tests/Atrea.PolicyEngine.Tests/TestResults/coverage.${{ matrix.dotnet }}.info

  coverage:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [netcoreapp3.1] # only upload one coverage report
    steps:
    - uses: actions/checkout@v3
    - name: Download Code Coverage Results
      uses: actions/download-artifact@v3
      with:
        name: code-coverage-report-${{ matrix.dotnet }}
    - name: Publish Coverage Report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.${{ matrix.dotnet }}.info
