name: Publish to NuGet
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Build, Pack & Publish

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: cd src && dotnet restore
    - name: Build
      run: cd src && dotnet build --configuration Release --no-restore
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/Atrea.PolicyEngine/Atrea.PolicyEngine.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
